# File: .github/workflows/deploy.yml

name: Publish site to GitHub Pages

# 1) Run this workflow on any push to 'main'
# 2) Also allow manual dispatch from the Actions tab (optional)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build on main, then push to gh-pages
    runs-on: ubuntu-latest

    steps:
      # Step A: check out your main branch
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # so we have the full history if we need to push back to gh-pages

      # Step B (optional): set up Node.js (only if your site is built with npm)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'   # or whatever version you require

      # Step C (optional): install dependencies and build
      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build
        # └─ this should produce static files into ./build (or ./dist or etc.)
      
      # Step D: push those built files into gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages       # ← the branch you use for Pages
          publish_dir: ./build            # ← adjust if your build outputs to a different folder
