# File: .github/workflows/pages.yml
name: pages build and deployment

# Whenever someone pushes to 'main', or you manually dispatch this workflow,
# GitHub will build & push to gh-pages for you.
on:
  push:
    branches:
      - main

  # Optional: so you can go to Actions → pages build and click “Run workflow” by hand.
  workflow_dispatch: 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) (If you have a Node-based build) set up Node and install dependencies.
      #    If your site is plain HTML/CSS/JS with no build step, you can delete 
      #    these Node‐related steps and publish “./” instead of “./build”.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build
        # (Assumes your repo has a package.json with a “build” script 
        #  that outputs static files into ./build)

      # 3) Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
